In [2]:
import xarray as xr
import numpy as np
import os
from pynwb import NWBHDF5IO

In [4]:
base_path = 'F:/vbn_s3_cache/visual-behavior-neuropixels-0.5.0/behavior_ecephys_sessions'
session_id = 1044385384
filepath = f'{base_path}/session_{session_id}/ecephys_session_{session_id}.nwb'
if not os.path.exists(filepath): print(f'Session {session_id} does not exist')
io = NWBHDF5IO(filepath, mode="r")
nwb_file = io.read()

In [33]:
nwb_file

root pynwb.file.NWBFile at 0x2313232084656
Fields:
  acquisition: {
    EyeTracking <class 'abc.EllipseEyeTracking'>,
    v_in <class 'pynwb.base.TimeSeries'>,
    v_sig <class 'pynwb.base.TimeSeries'>
  }
  devices: {
    NP.1 <class 'pynwb.device.Device'>,
    probeB <class 'abc.EcephysProbe'>,
    probeC <class 'abc.EcephysProbe'>,
    probeD <class 'abc.EcephysProbe'>,
    probeE <class 'abc.EcephysProbe'>,
    probeF <class 'abc.EcephysProbe'>
  }
  electrode_groups: {
    probeB <class 'abc.EcephysElectrodeGroup'>,
    probeC <class 'abc.EcephysElectrodeGroup'>,
    probeD <class 'abc.EcephysElectrodeGroup'>,
    probeE <class 'abc.EcephysElectrodeGroup'>,
    probeF <class 'abc.EcephysElectrodeGroup'>
  }
  electrodes: electrodes <class 'hdmf.common.table.DynamicTable'>
  file_create_date: [datetime.datetime(2023, 11, 29, 9, 54, 59, 613517, tzinfo=tzutc())]
  identifier: 1044385384
  institution: Allen Institute for Brain Science
  intervals: {
    Natural_Images_Lum_Matched_set_ophys_G_2019_presentations <class 'pynwb.epoch.TimeIntervals'>,
    flash_250ms_presentations <class 'pynwb.epoch.TimeIntervals'>,
    gabor_20_deg_250ms_presentations <class 'pynwb.epoch.TimeIntervals'>,
    spontaneous_presentations <class 'pynwb.epoch.TimeIntervals'>,
    trials <class 'pynwb.epoch.TimeIntervals'>
  }
  keywords: <StrDataset for HDF5 dataset "keywords": shape (3,), type "|O">
  lab_meta_data: {
    metadata <class 'abc.BehaviorMetadata'>,
    task_parameters <class 'abc.BehaviorTaskParameters'>
  }
  processing: {
    eye_tracking_rig_metadata <class 'pynwb.base.ProcessingModule'>,
    licking <class 'pynwb.base.ProcessingModule'>,
    optotagging <class 'pynwb.base.ProcessingModule'>,
    rewards <class 'pynwb.base.ProcessingModule'>,
    running <class 'pynwb.base.ProcessingModule'>,
    stimulus <class 'pynwb.base.ProcessingModule'>
  }
  session_description: EPHYS_1_images_G_5uL_reward
  session_start_time: 2020-08-19 21:47:08+00:00
  stimulus_template: {
    Natural_Images_Lum_Matched_set_ophys_G_2019.05.26 <class 'abc.StimulusTemplate'>
  }
  subject: subject abc.BehaviorSubject at 0x2313232083600
Fields:
  age: P151D
  age__reference: birth
  description: A visual behavior subject with a LabTracks ID
  genotype: wt/wt
  reporter_line: None
  sex: F
  species: Mus musculus
  subject_id: 524761

  timestamps_reference_time: 2020-08-19 21:47:08+00:00
  trials: trials <class 'pynwb.epoch.TimeIntervals'>
  units: units <class 'pynwb.misc.Units'>

In [35]:
import pandas as pd

In [54]:
stims = list(nwb_file.intervals.keys())[:-1]
collection = [nwb_file.intervals[stim].to_dataframe() for stim in stims]
collection = pd.concat(collection)
collection = collection.sort_values('start_time')
collection.index = np.arange(len(collection))
collection.index.name = 'id'

In [60]:
channel_table = pd.read_csv(f'F:/vbn_s3_cache/visual-behavior-neuropixels-0.5.0/project_metadata/channels.csv')

In [62]:
channel_table[channel_table['ecephys_session_id'] == session_id]

,ecephys_channel_id,ecephys_probe_id,ecephys_session_id,probe_channel_number,probe_vertical_position,probe_horizontal_position,anterior_posterior_ccf_coordinate,dorsal_ventral_ccf_coordinate,left_right_ccf_coordinate,structure_acronym,unit_count,valid_data
2304,1049369880,1044506933,1044385384,0,20.0,43.0,8167.0,4147.0,7337.0,PoT,0,True
2305,1049369881,1044506933,1044385384,1,20.0,11.0,8166.0,4138.0,7338.0,PoT,8,True
2306,1049369882,1044506933,1044385384,2,40.0,59.0,8165.0,4128.0,7339.0,PoT,2,True
2307,1049369883,1044506933,1044385384,3,40.0,27.0,8165.0,4119.0,7341.0,PoT,2,True
2308,1049369884,1044506933,1044385384,4,60.0,43.0,8164.0,4110.0,7342.0,PoT,3,True
...,...,...,...,...,...,...,...,...,...,...,...,...
4219,1049372814,1044506937,1044385384,379,3800.0,27.0,7567.0,796.0,9311.0,root,0,True
4220,1049372818,1044506937,1044385384,380,3820.0,43.0,7563.0,788.0,9315.0,root,0,True
4221,1049372821,1044506937,1044385384,381,3820.0,11.0,7559.0,781.0,9318.0,root,0,True
4222,1049372825,1044506937,1044385384,382,3840.0,59.0,7555.0,773.0,9322.0,root,0,True
4223,1049372829,1044506937,1044385384,383,3840.0,27.0,7551.0,766.0,9326.0,root,0,True

In [57]:
nwb_file.electrodes.to_dataframe()

,location,group,group_name,probe_vertical_position,probe_horizontal_position,probe_id,probe_channel_number,valid_data,x,y,z,imp,filtering
id,,,,,,,,,,,,,
1049369880,PoT,probeB abc.EcephysElectrodeGroup at 0x23132376...,probeB,20,43,1044506933,0,True,8167.0,4147.0,7337.0,NaN,AP band: 500 Hz high-pass; LFP band: 1000 Hz l...
1049369881,PoT,probeB abc.EcephysElectrodeGroup at 0x23132376...,probeB,20,11,1044506933,1,True,8166.0,4138.0,7338.0,NaN,AP band: 500 Hz high-pass; LFP band: 1000 Hz l...
1049369882,PoT,probeB abc.EcephysElectrodeGroup at 0x23132376...,probeB,40,59,1044506933,2,True,8165.0,4128.0,7339.0,NaN,AP band: 500 Hz high-pass; LFP band: 1000 Hz l...
1049369883,PoT,probeB abc.EcephysElectrodeGroup at 0x23132376...,probeB,40,27,1044506933,3,True,8165.0,4119.0,7341.0,NaN,AP band: 500 Hz high-pass; LFP band: 1000 Hz l...
1049369884,PoT,probeB abc.EcephysElectrodeGroup at 0x23132376...,probeB,60,43,1044506933,4,True,8164.0,4110.0,7342.0,NaN,AP band: 500 Hz high-pass; LFP band: 1000 Hz l...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1049372814,root,probeF abc.EcephysElectrodeGroup at 0x23132314...,probeF,3800,27,1044506937,379,True,7567.0,796.0,9311.0,NaN,AP band: 500 Hz high-pass; LFP band: 1000 Hz l...
1049372818,root,probeF abc.EcephysElectrodeGroup at 0x23132314...,probeF,3820,43,1044506937,380,True,7563.0,788.0,9315.0,NaN,AP band: 500 Hz high-pass; LFP band: 1000 Hz l...
1049372821,root,probeF abc.EcephysElectrodeGroup at 0x23132314...,probeF,3820,11,1044506937,381,True,7559.0,781.0,9318.0,NaN,AP band: 500 Hz high-pass; LFP band: 1000 Hz l...
1049372825,root,probeF abc.EcephysElectrodeGroup at 0x23132314...,probeF,3840,59,1044506937,382,True,7555.0,773.0,9322.0,NaN,AP band: 500 Hz high-pass; LFP band: 1000 Hz l...
1049372829,root,probeF abc.EcephysElectrodeGroup at 0x23132314...,probeF,3840,27,1044506937,383,True,7551.0,766.0,9326.0,NaN,AP band: 500 Hz high-pass; LFP band: 1000 Hz l...

In [63]:
from allensdk.brain_observatory.behavior.behavior_project_cache import VisualBehaviorNeuropixelsProjectCache
output_dir = r'F:\vbn_s3_cache'
cache = VisualBehaviorNeuropixelsProjectCache.from_s3_cache(output_dir)

c:\Users\Marisol\anaconda3\envs\allensdk\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [64]:
session = cache.get_ecephys_session(1044385384)

In [66]:
import sys
sys.getsizeof(session)

48

In [80]:
sp = session.stimulus_presentations
sp[sp['stimulus_block']==5]

,stimulus_block,image_name,duration,start_time,end_time,start_frame,end_frame,is_change,is_image_novel,omitted,...,contrast,active,color,temporal_frequency,orientation,stimulus_index,spatial_frequency,position_x,rewarded,stimulus_name
stimulus_presentations_id,,,,,,,,,,,,,,,,,,,,,
8597,5,im036_r,0.250206,5182.507728,5182.757934,307405,307420,False,False,False,...,NaN,False,NaN,NaN,NaN,-99,NaN,NaN,False,Natural_Images_Lum_Matched_set_ophys_G_2019
8598,5,im036_r,0.250206,5183.258345,5183.508551,307450,307465,False,False,False,...,NaN,False,NaN,NaN,NaN,-99,NaN,NaN,False,Natural_Images_Lum_Matched_set_ophys_G_2019
8599,5,im036_r,0.250212,5184.008974,5184.259186,307495,307510,False,False,False,...,NaN,False,NaN,NaN,NaN,-99,NaN,NaN,False,Natural_Images_Lum_Matched_set_ophys_G_2019
8600,5,im036_r,0.250211,5184.759609,5185.009819,307540,307555,False,False,False,...,NaN,False,NaN,NaN,NaN,-99,NaN,NaN,False,Natural_Images_Lum_Matched_set_ophys_G_2019
8601,5,im036_r,0.250209,5185.510241,5185.760450,307585,307600,False,False,False,...,NaN,False,NaN,NaN,NaN,-99,NaN,NaN,False,Natural_Images_Lum_Matched_set_ophys_G_2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13392,5,im115_r,0.250211,8782.437648,8782.687859,523220,523235,False,False,False,...,NaN,False,NaN,NaN,NaN,-99,NaN,NaN,False,Natural_Images_Lum_Matched_set_ophys_G_2019
13393,5,im115_r,0.250212,8783.188282,8783.438494,523265,523280,False,False,False,...,NaN,False,NaN,NaN,NaN,-99,NaN,NaN,False,Natural_Images_Lum_Matched_set_ophys_G_2019
13394,5,im115_r,0.250211,8783.938916,8784.189127,523310,523325,False,False,False,...,NaN,False,NaN,NaN,NaN,-99,NaN,NaN,False,Natural_Images_Lum_Matched_set_ophys_G_2019
13395,5,im115_r,0.250207,8784.689546,8784.939752,523355,523370,False,False,False,...,NaN,False,NaN,NaN,NaN,-99,NaN,NaN,False,Natural_Images_Lum_Matched_set_ophys_G_2019
13396,5,im115_r,0.250209,8785.440165,8785.690375,523400,523415,False,False,False,...,NaN,False,NaN,NaN,NaN,-99,NaN,NaN,False,Natural_Images_Lum_Matched_set_ophys_G_2019

In [98]:
from process_nwb import session as ss

In [97]:
import importlib
importlib.reload(process_nwb)

In [99]:
session_obj = ss(session_id)

In [126]:
session_obj.units

,PT_ratio,amplitude,amplitude_cutoff,cluster_id,cumulative_drift,d_prime,firing_rate,isi_violations,isolation_distance,l_ratio,...,presence_ratio,quality,recovery_slope,repolarization_slope,silhouette_score,snr,spread,velocity_above,velocity_below,waveform_duration
id,,,,,,,,,,,,,,,,,,,,,
1049374910,0.001205,167.157120,0.003587,489,125.59,5.182430,8.577549,0.009934,70.970062,0.001430,...,0.99,good,-0.003983,0.608682,0.159419,4.379133,70.0,1.579564,0.000000,0.796650
1049374988,0.028738,137.207558,0.021714,567,81.35,5.067903,0.547925,0.000000,47.149651,0.003139,...,0.93,good,NaN,0.209681,0.144932,2.717096,80.0,-0.018561,0.343384,2.101508
1049374987,0.091745,56.080635,0.500000,566,748.58,1.858911,1.545047,0.692976,29.801954,0.059517,...,0.99,noise,-0.000316,0.087476,-0.084957,0.724788,170.0,0.423506,1.201843,0.934003
1049374986,0.278659,100.392922,0.500000,565,1256.75,2.828780,0.260672,0.566091,36.519455,0.010127,...,0.99,good,-0.120240,0.060973,NaN,1.364341,80.0,0.007425,-2.060302,1.057621
1049374985,0.074544,98.648940,0.417832,564,154.86,3.191405,0.559624,0.859766,34.428405,0.011600,...,0.53,noise,NaN,0.118119,NaN,1.490112,80.0,-0.070533,0.686767,2.087772
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1049376616,0.567351,76.043662,0.007948,334,311.01,4.388272,1.984406,0.175829,55.967772,0.003624,...,0.99,good,-0.053436,0.226692,-0.016585,2.014150,120.0,0.882986,0.510170,0.549414
1049376347,0.570489,72.394823,0.205505,64,224.88,2.327467,0.184319,0.000000,31.913842,0.011035,...,0.99,good,-0.041960,0.199537,0.098651,2.100030,110.0,0.608279,0.255085,0.535678
1049376316,0.532536,130.525297,0.023873,33,189.48,4.071664,2.822566,1.265002,51.762422,0.012676,...,0.99,good,-0.102398,0.453310,0.091080,3.449538,70.0,-0.206030,0.000000,0.412060
1049376315,0.521396,193.495965,0.000590,32,89.89,5.729819,3.843607,0.939956,71.725429,0.002437,...,0.99,good,-0.199022,0.829290,0.175702,4.623059,50.0,0.000000,0.000000,0.219765
1049376314,0.484864,72.288645,0.141274,31,241.88,3.496439,3.337551,0.207192,63.351716,0.004148,...,0.99,good,-0.050052,0.250531,0.102159,2.010787,70.0,0.686767,-0.343384,0.439531

In [ ]:
session_obj.

,anterior_posterior_ccf_coordinate,dorsal_ventral_ccf_coordinate,filtering,left_right_ccf_coordinate,probe_channel_number,probe_horizontal_position,probe_id,probe_vertical_position,structure_acronym
id,,,,,,,,,
1049369880,8167.0,4147.0,AP band: 500 Hz high-pass; LFP band: 1000 Hz l...,7337.0,0,43,1044506933,20,PoT
1049369881,8166.0,4138.0,AP band: 500 Hz high-pass; LFP band: 1000 Hz l...,7338.0,1,11,1044506933,20,PoT
1049369882,8165.0,4128.0,AP band: 500 Hz high-pass; LFP band: 1000 Hz l...,7339.0,2,59,1044506933,40,PoT
1049369883,8165.0,4119.0,AP band: 500 Hz high-pass; LFP band: 1000 Hz l...,7341.0,3,27,1044506933,40,PoT
1049369884,8164.0,4110.0,AP band: 500 Hz high-pass; LFP band: 1000 Hz l...,7342.0,4,43,1044506933,60,PoT
...,...,...,...,...,...,...,...,...,...
1049372814,7567.0,796.0,AP band: 500 Hz high-pass; LFP band: 1000 Hz l...,9311.0,379,27,1044506937,3800,root
1049372818,7563.0,788.0,AP band: 500 Hz high-pass; LFP band: 1000 Hz l...,9315.0,380,43,1044506937,3820,root
1049372821,7559.0,781.0,AP band: 500 Hz high-pass; LFP band: 1000 Hz l...,9318.0,381,11,1044506937,3820,root
1049372825,7555.0,773.0,AP band: 500 Hz high-pass; LFP band: 1000 Hz l...,9322.0,382,59,1044506937,3840,root
1049372829,7551.0,766.0,AP band: 500 Hz high-pass; LFP band: 1000 Hz l...,9326.0,383,27,1044506937,3840,root

In [ ]:
session_obj.

AttributeError: 'BehaviorEcephysSession' object has no attribute 'get_probe_table'

In [111]:
probe_table = pd.read_csv(r"Z:\Buzsakilabspace\LabShare\NoamNitzan\Open_Access\Allen_2022\visual-behavior-neuropixels-0.4.0\project_metadata\probes.csv")
probe_table

,ecephys_probe_id,ecephys_session_id,name,sampling_rate,lfp_sampling_rate,phase,has_lfp_data,unit_count,channel_count,structure_acronyms,file_id
0,1044506933,1044385384,probeB,30000.178402,2500.014867,1.0,True,701,384,"['CA1', 'DG', 'LP', 'POL', 'PoT', 'VISpm', 'ro...",0
1,1044506934,1044385384,probeC,30000.049852,2500.004154,1.0,True,307,384,"['MB', 'MRN', 'POST', 'SCig', 'VISp', 'root']",1
2,1044506935,1044385384,probeD,30000.029115,2500.002426,1.0,True,521,384,"['CA1', 'CA3', 'DG', 'LGv', 'MB', 'TH', 'VISl'...",2
3,1044506936,1044385384,probeE,30000.075851,2500.006321,1.0,True,282,384,"['CA1', 'DG', 'MB', 'MGd', 'MGm', 'MRN', 'SGN'...",3
4,1044506937,1044385384,probeF,29999.959578,2499.996631,1.0,True,368,384,"['CA1', 'DG', 'LP', 'MRN', 'POL', 'PoT', 'SGN'...",4
...,...,...,...,...,...,...,...,...,...,...,...
900,1094073089,1093864136,probeE,30000.114385,2500.009532,1.0,False,319,384,"['CA1', 'CA3', 'DG', 'MB', 'MGv', 'PIL', 'PP',...",-999
901,1095249411,1095138995,probeC,30000.170489,2500.014207,1.0,False,457,384,"['HPF', 'MB', 'MRN', 'NB', 'POST', 'VISp', 'ro...",-999
902,1095460790,1095340643,probeC,30000.177408,2500.014784,1.0,False,355,384,"['MB', 'MRN', 'NB', 'POST', 'PRE', 'VISp', 'ro...",-999
903,1121524853,1121406444,probeB,29999.966074,2499.997173,1.0,False,345,384,"['APN', 'CA1', 'DG', 'LP', 'MB', 'ProS', 'VISp...",-999
904,1121744119,1121607504,probeB,29999.952799,2499.996067,1.0,False,265,384,"['APN', 'DG', 'LP', 'MB', 'ProS', 'VISpm', 'ro...",-999

In [113]:
session_probes = probe_table[probe_table['ecephys_session_id'] == session_id]
session_probes

,ecephys_probe_id,ecephys_session_id,name,sampling_rate,lfp_sampling_rate,phase,has_lfp_data,unit_count,channel_count,structure_acronyms,file_id
0,1044506933,1044385384,probeB,30000.178402,2500.014867,1.0,True,701,384,"['CA1', 'DG', 'LP', 'POL', 'PoT', 'VISpm', 'ro...",0
1,1044506934,1044385384,probeC,30000.049852,2500.004154,1.0,True,307,384,"['MB', 'MRN', 'POST', 'SCig', 'VISp', 'root']",1
2,1044506935,1044385384,probeD,30000.029115,2500.002426,1.0,True,521,384,"['CA1', 'CA3', 'DG', 'LGv', 'MB', 'TH', 'VISl'...",2
3,1044506936,1044385384,probeE,30000.075851,2500.006321,1.0,True,282,384,"['CA1', 'DG', 'MB', 'MGd', 'MGm', 'MRN', 'SGN'...",3
4,1044506937,1044385384,probeF,29999.959578,2499.996631,1.0,True,368,384,"['CA1', 'DG', 'LP', 'MRN', 'POL', 'PoT', 'SGN'...",4

In [122]:
probe_table = pd.read_csv(r"Z:\Buzsakilabspace\LabShare\NoamNitzan\Open_Access\Allen_2022\visual-behavior-neuropixels-0.4.0\project_metadata\probes.csv")
session_probes = probe_table[probe_table['ecephys_session_id'] == session_id]
qualified_probes = []
for probe_id in session_probes.ecephys_probe_id.values:
    probe = session_probes[session_probes['ecephys_probe_id'] == probe_id]
    if ('VISp' in probe.structure_acronyms.values[0]) and ('VISpm' not in probe.structure_acronyms.values[0]):
        qualified_probes.append(probe_id)
if len(qualified_probes) == 0:
    print(f'No qualified probes for session {session_id}')
elif len(qualified_probes) > 1:
    print(f'More than one qualified probes for session {session_id}')
    print('Choosing the first one')
    probe_id = qualified_probes[0]
else:
    print(f'One qualified probe for session {session_id}')
    probe_id = qualified_probes[0]
probe_letter = probe_table[probe_table['ecephys_probe_id'] == probe_id].name.values[0][-1]
print(f'Probe {probe_id}, (probe{probe_letter}) is chosen for session')

One qualified probe for session 1044385384
Probe 1044506934, (probeC) is chosen for session

In [123]:
probe_table

,ecephys_probe_id,ecephys_session_id,name,sampling_rate,lfp_sampling_rate,phase,has_lfp_data,unit_count,channel_count,structure_acronyms,file_id
0,1044506933,1044385384,probeB,30000.178402,2500.014867,1.0,True,701,384,"['CA1', 'DG', 'LP', 'POL', 'PoT', 'VISpm', 'ro...",0
1,1044506934,1044385384,probeC,30000.049852,2500.004154,1.0,True,307,384,"['MB', 'MRN', 'POST', 'SCig', 'VISp', 'root']",1
2,1044506935,1044385384,probeD,30000.029115,2500.002426,1.0,True,521,384,"['CA1', 'CA3', 'DG', 'LGv', 'MB', 'TH', 'VISl'...",2
3,1044506936,1044385384,probeE,30000.075851,2500.006321,1.0,True,282,384,"['CA1', 'DG', 'MB', 'MGd', 'MGm', 'MRN', 'SGN'...",3
4,1044506937,1044385384,probeF,29999.959578,2499.996631,1.0,True,368,384,"['CA1', 'DG', 'LP', 'MRN', 'POL', 'PoT', 'SGN'...",4
...,...,...,...,...,...,...,...,...,...,...,...
900,1094073089,1093864136,probeE,30000.114385,2500.009532,1.0,False,319,384,"['CA1', 'CA3', 'DG', 'MB', 'MGv', 'PIL', 'PP',...",-999
901,1095249411,1095138995,probeC,30000.170489,2500.014207,1.0,False,457,384,"['HPF', 'MB', 'MRN', 'NB', 'POST', 'VISp', 'ro...",-999
902,1095460790,1095340643,probeC,30000.177408,2500.014784,1.0,False,355,384,"['MB', 'MRN', 'NB', 'POST', 'PRE', 'VISp', 'ro...",-999
903,1121524853,1121406444,probeB,29999.966074,2499.997173,1.0,False,345,384,"['APN', 'CA1', 'DG', 'LP', 'MB', 'ProS', 'VISp...",-999
904,1121744119,1121607504,probeB,29999.952799,2499.996067,1.0,False,265,384,"['APN', 'DG', 'LP', 'MB', 'ProS', 'VISpm', 'ro...",-999

In [127]:
session_obj.channels

,anterior_posterior_ccf_coordinate,dorsal_ventral_ccf_coordinate,filtering,left_right_ccf_coordinate,probe_channel_number,probe_horizontal_position,probe_id,probe_vertical_position,structure_acronym
id,,,,,,,,,
1049369880,8167.0,4147.0,AP band: 500 Hz high-pass; LFP band: 1000 Hz l...,7337.0,0,43,1044506933,20,PoT
1049369881,8166.0,4138.0,AP band: 500 Hz high-pass; LFP band: 1000 Hz l...,7338.0,1,11,1044506933,20,PoT
1049369882,8165.0,4128.0,AP band: 500 Hz high-pass; LFP band: 1000 Hz l...,7339.0,2,59,1044506933,40,PoT
1049369883,8165.0,4119.0,AP band: 500 Hz high-pass; LFP band: 1000 Hz l...,7341.0,3,27,1044506933,40,PoT
1049369884,8164.0,4110.0,AP band: 500 Hz high-pass; LFP band: 1000 Hz l...,7342.0,4,43,1044506933,60,PoT
...,...,...,...,...,...,...,...,...,...
1049372814,7567.0,796.0,AP band: 500 Hz high-pass; LFP band: 1000 Hz l...,9311.0,379,27,1044506937,3800,root
1049372818,7563.0,788.0,AP band: 500 Hz high-pass; LFP band: 1000 Hz l...,9315.0,380,43,1044506937,3820,root
1049372821,7559.0,781.0,AP band: 500 Hz high-pass; LFP band: 1000 Hz l...,9318.0,381,11,1044506937,3820,root
1049372825,7555.0,773.0,AP band: 500 Hz high-pass; LFP band: 1000 Hz l...,9322.0,382,59,1044506937,3840,root
1049372829,7551.0,766.0,AP band: 500 Hz high-pass; LFP band: 1000 Hz l...,9326.0,383,27,1044506937,3840,root